[versions]
indra = "3.1.2"
kotlin = "1.8.22"
spotless = "6.19.0"
dokka = "1.8.20"

[libraries]
indra-common = { group = "net.kyori", name = "indra-common", version.ref = "indra" }
indra-publishing-sonatype = { group = "net.kyori", name = "indra-publishing-sonatype", version.ref = "indra" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
dokka = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
